import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id "org.jetbrains.kotlin.jvm" version "2.3.10"
    id "org.jetbrains.kotlin.plugin.allopen" version "2.3.10"
    id "io.quarkus"
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation enforcedPlatform("io.netty:netty-bom:4.1.132.Final")
    implementation "io.quarkus:quarkus-arc"
    implementation "io.quarkus:quarkus-resteasy"
    implementation "io.quarkus:quarkus-resteasy-jackson"
    implementation "com.fasterxml.jackson.module:jackson-module-kotlin"

    implementation "io.quarkus:quarkus-websockets"
    implementation "io.quarkus:quarkus-smallrye-health"

    implementation "io.quarkus:quarkus-kotlin"

    implementation "io.quarkus:quarkus-config-yaml"

    implementation "io.github.microutils:kotlin-logging:3.0.5"

    testImplementation "io.quarkus:quarkus-junit5"
    testImplementation "io.quarkus:quarkus-junit5-mockito"
    testImplementation "org.mockito.kotlin:mockito-kotlin:3.2.0"

    testImplementation "io.rest-assured:rest-assured"
    testImplementation "io.kotest:kotest-assertions-core:5.8.0"
}

group = "yochess"
version = "1.0.0"

kotlin {
    jvmToolchain(25)
    compilerOptions {
        jvmTarget = JvmTarget.fromTarget("25")
        javaParameters = true
    }
}

test {
    systemProperty "java.util.logging.manager", "org.jboss.logmanager.LogManager"
}
allOpen {
    annotation("jakarta.ws.rs.Path")
    annotation("jakarta.enterprise.context.ApplicationScoped")
    annotation("io.quarkus.test.junit.QuarkusTest")
}
