quarkus:
  log:
    level: INFO
    category:
      "io.quarkus":
        level: INFO
    # https://quarkus.io/guides/logging#logging-format
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] [%c{2.}.%M] %-5p - %s%e%n"

"%staging":
  quarkus:
    http:
      ssl:
        certificate:
          key-store-file: /deployments/cert/keystore.p12
          key-store-password: staging
          key-store-file-type: PKCS12
      port: 8443
      insecure-requests: disabled
